baseURL = "https://yohanesmario.com/"
title = "Mario's Blog"
copyright = "Copyright © 2024, Yohanes Mario Chandra; all rights reserved."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-21809588-1"
theme = "PaperMod"
enableEmoji = true
summaryLength = 30
ignoreFiles = [ "README.md" ]
enableRobotsTXT = true
newContentEditor = "code"

[security]
  enableInlineShortcodes = true

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', 'code']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[permalinks]
  posts = "/article/:title/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10
  [[menu.main]]
    identifier = "biography"
    name = "Biography"
    url = "/biography/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  ShowReadingTime = true
  ShowAllPagesInArchive = true

  [params.profileMode]
    enabled = true
    title = "Yohanes Mario Chandra"
    subtitle = "Courage, kindness, never give up."
    imageUrl = "https://gravatar.com/userimage/12748246/c3cfdfb564e9ad44619173310a69a14f.jpeg?size=256" # optional
    imageTitle = "Profile Picture" # optional
    imageWidth = 180 # custom size
    imageHeight = 180 # custom size
  
  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/yohanesmario"
  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/yohanesmario"
  [[params.socialIcons]]
    name = "X"
    url = "https://x.com/yohanesmario"
  [[params.socialIcons]]
    name = "Facebook"
    url = "https://www.facebook.com/yohanesmario"
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:yohanes.mc@gmail.com"
  
  [params.assets]
    disableFingerprinting = true
